name: 'Determine Publish Version'
description: 'Determine the version to publish based on commit history and semantic versioning'

inputs:
  prerelease:
    description: "[boolean: 'true'/'false'] Whether this is a prerelease (appends -rc.N suffix)"
    required: false
    default: 'false'
  openai-api-key:
    description: '[secret] OpenAI API key for AI-powered version detection'
    required: true

outputs:
  version:
    description: 'The determined version (e.g., 1.2.3 or 1.2.3-rc.5)'
    value: ${{ steps.version.outputs.final }}
  previous-version:
    description: 'The previous version before this release'
    value: ${{ steps.last-release.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Get last release info
      id: last-release
      uses: actions/github-script@v7
      with:
        script: |
          try {
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            
            if (releases.length > 0) {
              const tagName = releases[0].tag_name;
              const { data: ref } = await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tagName}`
              });
              core.setOutput('sha', ref.object.sha);
              core.setOutput('version', tagName.replace(/^v/, ''));
            } else {
              const allCommits = await github.paginate(github.rest.repos.listCommits, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100
              });
              core.setOutput('sha', allCommits[allCommits.length - 1].sha);
              core.setOutput('version', '0.0.0');
            }
          } catch (error) {
            core.setOutput('sha', context.sha);
            core.setOutput('version', '0.0.0');
          }

    - name: AI Determine Version
      id: ai-version
      uses: openai/codex-action@v1
      with:
        openai-api-key: ${{ inputs.openai-api-key }}
        safety-strategy: read-only
        prompt: |
          Analyze commits between ${{ steps.last-release.outputs.sha }} and ${{ github.sha }}.
          Current version: ${{ steps.last-release.outputs.version }}
          Prerelease: ${{ inputs.prerelease }}
          
          Rules:
          - BREAKING CHANGE or ! = major bump
          - feat: = minor bump  
          - fix:, perf:, or other = patch bump
          - Default to patch if unclear
          - For prereleases: use same version logic, suffix will be added automatically
          
          Respond with ONLY X.Y.Z

    - name: Parse Version
      id: version
      shell: bash
      run: |
        RAW_OUTPUT="${{ steps.ai-version.outputs.final-message }}"
        echo "Raw AI version output: '${RAW_OUTPUT}'"
        
        if [ -z "$RAW_OUTPUT" ]; then
          echo "::error::AI version step produced no output. Check that 'ai-version' step ran successfully."
          exit 1
        fi
        
        NEXT=$(echo "$RAW_OUTPUT" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        
        if [ -z "$NEXT" ]; then
          echo "::error::Could not parse semantic version (X.Y.Z) from AI output: '${RAW_OUTPUT}'"
          exit 1
        fi
        
        if [ "${{ inputs.prerelease }}" == "true" ]; then
          echo "final=${NEXT}-rc.${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
        else
          echo "final=${NEXT}" >> $GITHUB_OUTPUT
        fi
        
        echo "Determined version: ${NEXT}"
